👷🔧 Add CI workflow for automatic linting and formatting
CodingGarden/fresh-spots pull request #63
Opened 2022-11-18 15:40 UTC by drillskibo

This workflow sets an action to be ran automatically on push. It uses the latest version of Ubuntu, setups Deno, then runs the linter and the formatter.

2022-11-18 15:40 UTC, drillskibo commented
Closes #62.

2022-11-18 15:44 UTC, drillskibo commented
I'm not sure if `--check` flag should be used or not.
Maybe @omar2205 knows ?

2022-11-18 16:28 UTC, omar2205 commented
> I'm not sure if `--check` flag should be used or not. Maybe @omar2205 knows ?

running `deno fmt` will try and fix (write), using `--check` will throw an error

2022-11-19 01:09 UTC, omar2205 requested changes

2022-11-19 01:09 UTC, omar2205 commented on .github/workflows/deno-ci.yml
> +on: push
Better to listen to PRs too. 
`on: [push, pull_request]`

2022-11-19 01:13 UTC, omar2205 commented on .github/workflows/deno-ci.yml
> +on: push
This way, we can see a failed check in the PR if `deno fmt --check` fails

2022-11-19 18:00 UTC, merged